name: Deploy Cloudflare Worker

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  deploy-web:
    name: Deploy Kaiapay Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            npm run deploy:production
          else
            npm run deploy:development
          fi

  create-release:
    name: Create Production Release Draft
    needs: [deploy-web]
    runs-on: ubuntu-latest
    # always run this job, but fail if any of the dependent jobs failed (not skipped)
    if: ${{ always() && !contains(join(needs.*.result, ','), 'fail') && github.event_name != 'release' }}
    permissions:
      contents: write
    steps:
      - name: Create Release Tag
        id: create-release-tag
        run: echo "tag_name=r-$(printf %06d $GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-release-tag.outputs.tag_name }}
          name: Release ${{ steps.create-release-tag.outputs.tag_name }}
          generate_release_notes: true
          token: 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
          draft: ${{ !contains(github.event.head_commit.message, 'CHECKED') }}
